@startsalt
' Árbol de componentes de la aplicación de búsqueda de productos
    {
        {T
            +App
            ++ Router
            +++ ListaProductos
            +++ DetalleProducto
        }
    }
@endsalt