@startuml
  ' Clases del sistema de buscador
  class User {
    +id: string
    +email: string
    +role: role
  }

  class enum {
    Role
    Admin
    Editor
    Viewer
  }

  class Post {
    +id: string
    +title: string
    +content: string
    +authorId: string
  }

  User <-- Post
@enduml